Add a $command variable, and colorize summary
bats-core/bats-core pull request #444
Opened 2021-05-11 00:25 UTC by msterin

Fixes #163 

Motivation:
* See https://github.com/bats-core/bats-core/issues/163 for $command motivation. I second it and also it's helpful when the command passed to `run` contains multiple shell vars, so $command shows the final.
* Our test pass is fairly long and it's super convenient to have colorized summary (pass/fail) at the end of manual runs

We use bats with these fixes for a long time now, time for a PR.

- [x] I have reviewed the [Contributor Guidelines][contributor].
- [x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

2021-05-11 08:39 UTC, martin-schulze-vireso requested changes
Thanks for this PR. Could you add tests for these new features.

2021-06-06 09:49 UTC, martin-schulze-vireso commented
I am still mulling over whether it is okay to use `$command`. It sure is in line with the other variables (`$output`, `$lines`, `$status`). However, the new `$command` might break existing code of the form:

```
command="some user defined value"
run some command # overrides $command's value
[ "$command" = "some user defined value"] # expectation is for the old, user defined value
```

@bats-core/bats-core What do you think? Should we proceed with this and place a big fat warning in the release notes? Should we use a name that is less likely to collide, like `bats_run_command`?

2021-06-09 02:21 UTC, msterin commented
Good point and  I am happy to change to whatever there is an agreement about, e.g. 

- `command_line` (reasonably aligned with other vars and IMO very unlikely to generate a conflict - google search for `"command_line" AND "bats" AND site:github.com` brings nothing) 
or
- `bats_run_command` 

Just let me know what's the maintainers' preference.

2021-06-09 12:37 UTC, rockandska commented
> @bats-core/bats-core What do you think? Should we proceed with this and place a big fat warning in the release notes? Should we use a name that is less likely to collide, like bats_run_command?

Not directly related to this PR (sorry to pollute @msterin), but in a general way, I think that all internal variables / functions used by bats and exposed in `@test` should have a prefix (bats_) to avoid collision with tested code at maximum.
As consequences, external libraries / users tests will break and should be changed in a major release.

2021-07-25 07:02 UTC, martin-schulze-vireso commented
This might become obsolete through #467 which (currently) adds `BATS_TRACE_COMMAND`.

2021-07-25 14:22 UTC, NorseGaud commented
@martin-schulze-vireso , they look compatible. I added the code manually to test it out and it seems to work.

2021-07-27 10:24 UTC, NorseGaud commented
@msterin , you going to continue with getting this ready? If not, I'd like to take over and handle it.

2021-07-27 20:51 UTC, msterin commented
> @msterin , you going to continue with getting this ready? If not, I'd like to take over and handle it.

@NorseGaud Please, do take over - I just started a new job and will have very limited cycles for a while.  Appreciate it.

2021-07-27 21:00 UTC, NorseGaud commented
> > @msterin , you going to continue with getting this ready? If not, I'd like to take over and handle it.
> 
> @NorseGaud Please, do take over - I just started a new job and will have very limited cycles for a while. Appreciate it.

Best of luck with the new job! That's exciting!

2021-07-28 01:31 UTC, NorseGaud commented
@martin-schulze-vireso I'm going to figure out how to do this in my existing --trace branch. You can close this PR.

2021-07-28 02:15 UTC, closed without merging