improve grammar for 'return variable' gotcha
bats-core/bats-core pull request #464
Opened 2021-07-05 09:50 UTC by ad8-bdl

The current version reads poorly to me.

- [ x] I have reviewed the [Contributor Guidelines][contributor].
- [ x] I have reviewed the [Code of Conduct][coc] and agree to abide by it

[contributor]: https://github.com/bats-core/bats-core/blob/master/docs/CONTRIBUTING.md
[coc]:         https://github.com/bats-core/bats-core/blob/master/docs/CODE_OF_CONDUCT.md

2021-07-05 10:10 UTC, martin-schulze-vireso requested changes

2021-07-06 06:08 UTC, ad8-bdl commented on docs/source/gotchas.rst
> +How can I test functions that return their results via a variable?
sgtm, fixed

2021-07-06 07:38 UTC, martin-schulze-vireso approved these changes

2021-07-06 07:38 UTC, martin-schulze-vireso commented on docs/source/gotchas.rst
> +How can I test functions that return their results via a variable?
sgtm?

2021-07-06 08:00 UTC, merged

2021-07-06 08:01 UTC, martin-schulze-vireso commented
I had rebase to sign the commits and squashed them too.

2021-07-06 08:08 UTC, ad8-bdl commented on docs/source/gotchas.rst
> +How can I test functions that return their results via a variable?
sorry, sgtm = "sounds good to me" :-)

2021-07-06 08:13 UTC, martin-schulze-vireso commented on docs/source/gotchas.rst
> +How can I test functions that return their results via a variable?
Okay, thanks for the clarification.